### ISSUE TITLE
Can't compile under linux

### ISSUE THREAD

**Issue by emdio** [Zerbinati/SugaR-AI#1]
[sugar_ai_comp_errrors.txt](https://github.com/Zerbinati/SugaR-AI/files/5695223/sugar_ai_comp_errrors.txt)
After cloning the repo and running the make command lot of errors happen. Attach txt file

**Comment by Zerbinati** [comment]
[https://www.mediafire.com/file/r95org0rd2bvkd0/src.zip/file](url)
Please use this SRC
