### ISSUE TITLE
SugaR AI Experience Tools 1.03

### ISSUE THREAD

**Issue by nguyencongminh090** [Zerbinati/SugaR-AI#10]
I can't open SugaR AI Experience Tools 1.03 on my computer Win7 64bit.

**_Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	SugaR AI Experience Tools.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	dd6da5af
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.2053.0
  Problem Signature 06:	58fa6bc1
  Problem Signature 07:	2d2d
  Problem Signature 08:	2f
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	7598
  Additional Information 2:	75981ec03177ed13808f21220cbc4863
  Additional Information 3:	57e0
  Additional Information 4:	57e01d0b3f39a0c8bcb8224a6bf26935_**

It only happens when I run on window 7 but I can run it on window 10.

**Comment by khalid-a-omar** [comment]
Sugar AI Tools is built on top of Microsoft .NET 4.5.2, which I guess is already present on Windows 10 but not Windows 7

You will need to install it from this link: https://www.microsoft.com/en-us/download/details.aspx?id=42642

**Comment by khalid-a-omar** [comment]
Actually, I stand corrected. This problem is not due to the missing .NET version or at least not only due to that!

I have fixed the problem in the code. Marco is going to release a new exe soon
