### ISSUE TITLE
Compile Error at Apple/MacOS/M1

### ISSUE THREAD

**Issue by acepoint** [Zerbinati/SugaR-AI#15]
Hi folks,

for a few weeks now I'm compiling a lot of chess stuff for Apple's M1, arm64 ( [acepoint.de](https://acepoint.de) ). For the version 2.00 of SugaR I get an error which I can't solve:

`
make profile-build COMP=clang ARCH=apple-silicon
...`
`experience.cpp:1254:27: error: implicit instantiation of undefined template
      'std::__1::basic_istringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
            istringstream iss(str);
                          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:133:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_istringstream;
                               ^
1 error generated.
make[2]: *** [experience.o] Error 1
make[1]: *** [clang-profile-make] Error 2
make: *** [profile-build] Error 2`

**Comment by Zerbinati** [comment]
These questions should be asked in the forum not here.
https://outskirts.altervista.org/forum/index.php
