### ISSUE TITLE
Error while compile V2 - MacOS

### ISSUE THREAD

**Issue by ArminHHJ** [Zerbinati/SugaR-AI#16]
last compile v1.8 works fine without errors (now and few days ago)
Use:     make -j build ARCH=x86-64-bmi2 COMP=clang
Now I get this error (also I use gcc instead clang):

experience.cpp:1254:27: error: implicit instantiation of undefined template
      'std::__1::basic_istringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
            istringstream iss(str);
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:133:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_istringstream;
                               ^
1 error generated.
make[1]: *** [experience.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build] Error 2

**Comment by ArminHHJ** [comment]
Sorry, maybe I missed it. Is there a solution to the problem?

**Comment by Zerbinati** [comment]
I replied to your PM in the CSS Forum
