### ISSUE TITLE
info string Could not open experience file: SugaR.exp

### ISSUE THREAD

**Issue by tidypy** [Zerbinati/SugaR-AI#19]
Error:  info string Could not open experience file: SugaR.exp

SCID GUI gives this error when trying to load:   
"SCID Error Code:  the analysis engine terminated without exit code: -- "

this is for all versions:  and every Git or archive Version I could find.

![2021-05-31 12_48_05-C__Users_Cadmin_Downloads_windows_build_SugaR AI 2 10 bmi2 exe](https://user-images.githubusercontent.com/50213641/120227351-98927d80-c20e-11eb-87da-ec4866f6afc8.png)

**Comment by Zerbinati** [comment]
You have to put the network in the same folder as the engine.
Scaricala qui:
https://tests.stockfishchess.org/api/nn/nn-7756374aaed3.nnue
The experience file is created later
that message indicates that there is no experience file in the same folder as the engine
