### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by patzer081** [Zerbinati/SugaR-AI#21]
Would it be possible to make this engine record experience without having to restart the engine after each match?

**Comment by khalid-a-omar** [comment]
Hello patzer081, thank you for your suggestion.

This is a very good suggestion. I have implemented this feature in Eman but did not add it to SugaR yet. I will add it in the next release of SugaR

**Comment by patzer081** [comment]
TYVM! Also,would it be possible to get a copy of your eman engine? I've looked all over the internet and I can't find it anywhere. Is this a private or commercial engine? Thanks in advance.

**Comment by khalid-a-omar** [comment]
You are welcome.

Unfortunately, Eman is now a private project for me only. I'm not distributing Eman publicly or privately.

**Comment by patzer081** [comment]
Ok thank you.  But I have another suggestion if it wouldn't be too complicated to inpliment or introduce bugs. If the engine sugar could possibly use Namilov table bases in combination with the Syzygy tablebases. For instance . When there are only 5 pieces or 6 picks on the board it could switch over to the namilov tablebases so as to play the moves instantly instead of longer waiting periods Wich is somewhat annoying in a blitz game. . If you change your mind on the eman engine privacy I would be overly joyed to obtain a copy lol. Thanks for reading

**Comment by patzer081** [comment]
To be more clear in the ya or base suggestion the engine would never probe the namilov bases. Only when there are 5-6 pieces on the board it could use them for the sake of speed. I hope my suggestion doesn't seem bad but it's just a thought. I'm not a software developer so I have no idea the struggles involved in implementing code

**Comment by tissatussa** [comment]
the engine Weiss uses an online TB called NoobBook, see https://github.com/TerjeKir/weiss/
it allow Weiss to query and play moves suggested by noobpwnftw's online opening database.
but i remember it uses some small delay per move to query this online DB to make it work, especially when playing itself ..

**Comment by patzer081** [comment]
Thank you. That's very interesting. I would prefer though that all Syzygy tablebases engines have the option to use namilov tablebases in combination as I mention d previously though stored on my own drives. This would totally get rid of the annoying search in 5-6 piece endings and for the sake of time would be very pleasant assuming that it would work flawlessly and not be buggy. Syzygy tablebases are superior in probes it's just when those final pieces are on the board the engine "thinks" and that's super anoying to me

**Comment by tissatussa** [comment]
@patzer081 sorry for the confusion : Weiss also has OnlineSyzygy, it allow Weiss to query online 7 piece Syzygy tablebases hosted by lichess .. i recently proposed that to the creator of Weiss and he managed to implement this UCI option within 48 hours ! At first, Weiss had only the online opening DB ..

but i can imagine you prefer the TBs on your harddrive ..

**Comment by patzer081** [comment]
I ran tests with the eman chimera that's available online and set sugar to play up until there are 5 pieces on the board and switch to an older engine that uses namilov table bases . The sheer speed of the instant moves when it can down to 5 pieces was so rewarding lol. That's the entire nature of my suggestion. Although chimera has huge problems from my testing. Once a match has ended and the game has unloaded an engine process will still be running using cpu without a game even being played and that's a huge problem. Only solution is to open the task manager and kill the engine process or close the GUI and reopen it hoping the engine process will stop but most of the time even after closing the GUI the engine is still running and using cpu. Another issue is that it will create many many instances of the same exact engine all of them using cpu. Some games I noticed when I saw it was dropping the kns down to less than 400 as it was its turn to play due to duplicate processes introduced by a new game with eman chimera.

**Comment by khalid-a-omar** [comment]
The Nalimov idea is interesting. I don't think it adds any ELO because ultimately Syzygy and Nalimov have the same data (except Nalimov has the actual moves). The only ELO difference can come from avoiding time losses if the engine is out of time.

I will keep it in mind, but I don't think it will be implemented in SugaR any time soon.

The idea of online TB is also interesting but could have bad side effects if there are network delays!

**Comment by patzer081** [comment]
You are correct it wouldn't add elo at all. It would just be more pleasant for time reasons. Thanks for your reply
