### ISSUE TITLE
Sugar ai experiance tools experience from pgn don't work

### ISSUE THREAD

**Issue by godpow** [Zerbinati/SugaR-AI#24]
Validating engine
Engine is valid
PGN to EXP -> Starting
Cleaning 1 PGN file (size = 2.26 MB)
Clean PGN size: 2.50 MB
Generating compact PGN -> 100.000%, Games: 3290 (rejected: 3290, errors: 0). Games/second: 8016.9. Time remaining: 00:00:00
Generating experience from compact PGN

  _           _  
 /_`   _  _  /_/ 
 _//_//_//_|/ \_
      __/
	  

SugaR AI 2.40  by Stockfish Team, Marco Zerbinati, Khalid Omar

Compiled by g++ (GNUC) 7.3.0 on MinGW64
Compilation settings include:  64bit AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 7.3.0

Build date/time    : 2021-Sep-03 12:09:32

Operating System (OS) : Windows 10 Client Or Greater
CPU Brand             : AMD Ryzen 7 3700X 8-Core Processor             
NUMA Nodes            : 1
Cores                 : 8
Threads               : 16
Hyper-Threading       : Yes
L1/L2/L3 cache size   : 512KB/4MB/32MB
Memory installed (RAM): 32GB

info string SugaR.exp -> Total moves: 18977. Total positions: 11125. Duplicate moves: 2. Fragmentation: 0.01%

Building experience from PGN: 
PGN to EXP -> Completed
	Compact PGN file: C:\Users\CyberKira\AppData\Local\Temp\Sugar UI Tools\compact.cpgn
	Experience file : C:\Users\CyberKira\Documents\Chess Engines\sugar\SugaR.exp
	Max ply         : 1000
	Max value       : 32000
	Depth range     : 4 - 246

   nan% -> Games: 0 (errors: 0), WBD: 0/0/0, Moves: 0 (0 with scores, 0 without scores, 0 ignored). Exp size: 0 B

**Comment by Zerbinati** [comment]
The tool works perfectly 100% tested
you must use games that include engine evaluation
