### ISSUE TITLE
Experience book

### ISSUE THREAD

**Issue by nguyencongminh090** [Zerbinati/SugaR-AI#9]
Sometimes SugaR takes a move with low evaluation into the experience book and it causes a loss. I think you should filter the evaluation before make it play as an open book.

**Comment by nguyencongminh090** [comment]
> Sometimes SugaR takes a move with low evaluation into the experience book and it causes a loss. I think you should filter the evaluation before make it play as an open book.

Experience book is very good if it can save a good move with high evaluation but it is bad if it also saves low evaluation. Hope you will fix it. Thanks

**Comment by nguyencongminh090** [comment]
> Sometimes SugaR takes a move with low evaluation into the experience book and it causes a loss. I think you should filter the evaluation before make it play as an open book.

Experience is very good if it can save high evaluation but it will be bad if it also saves bad moves with low evaluation. Hope you will fix it. Thanks

**Comment by khalid-a-omar** [comment]
Experience data contain the evaluation of the position, regardless if it is good or bad, low or high!

The information saved to the experience file also includes the depth of the evaluation. The engine will use experience information up to the given depth
